name: compile

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install requirements
        run: python3 -m pip install -r requirements.txt

      - name: Run build.sh
        run: ./build.sh
