name: Publish

on:
  workflow_dispatch:

jobs:


  build:
    name: Publish pdfs
    runs-on: ubuntu-latest
         
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install requirements
        run: python3 -m pip install -r requirements.txt

      - name: Install LaTex
        run: sudo apt-get install -y texlive-base texlive-xetex

      - name: Run generate_release.sh
        id: generate_release
        run: |
          source ./create_release.sh ${{ github.ref }}
          echo "::set-output name=ZIP_NAME::$zipname"

      # This step reads a file from repo and use it for body of the release
      # This works on any self-hosted runner OS
      - name: Read README.md and use it as a body of new release
        id: read_release
        shell: bash
        run: |
          r=$(cat output/README.md)                         # <--- Read README.md
          r="${r//'%'/'%25'}"                               # Multiline escape sequences for %
          r="${r//$'\n'/'%0A'}"                             # Multiline escape sequences for '\n'
          r="${r//$'\r'/'%0D'}"                             # Multiline escape sequences for '\r'
          echo "::set-output name=RELEASE_BODY::$r"         # <--- Set environment variable

      - name: Upload Binaries to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: ${{ steps.generate_release.outputs.ZIP_NAME }}
          asset_name: ${{ steps.generate_release.outputs.ZIP_NAME }}
          body: |
            ${{ steps.read_release.outputs.RELEASE_BODY }}  # <--- Use environment variables that was created earlier
